const dict = {
  zh: {
    title: '{city}内涝地图',
    city: '城市',
    drainage: '排水效率',
    drainageHint: '拖动模拟排水系统好坏',
    now: '现在',
    estimated: '过去（估计）',
    predicted: '未来（预测）',
    bandNone: '无明显积水',
    bandPossible: '可能积水',
    bandSevere: '严重积水',
    legendDisclaimer: '模型估算，非实测数据',
    showElevation: '显示地形高程',
    elevationUnit: '米',
    contourInterval: '等高线间隔',
    coverageNote: '虚线内为数据范围，线外无地形数据',
    contourDetail: '等高线精度',
    contourSmoothed: '插值平滑，非更高精度地形',
    updatedAt: '数据更新于',
    coverage: '数据覆盖',
    loading: '数据加载中…',
    noData: '暂无降雨数据，请稍后刷新',
    reports: '积水报告',
    langToggle: 'EN',
    aboutBtn: '关于',
    tourBtn: '教程',
    introTagline: '结合实时降雨与卫星地形，估算城市街道哪里可能积水——过去 24 小时到未来 48 小时。',
    introUsesHeading: '有什么用',
    introUseDrivingTitle: '开车出行',
    introUseDriving: '出发前查看路线上的低洼路段，绕开可能积水的下穿隧道和涵洞。',
    introUsePreventTitle: '防涝准备',
    introUsePrevent: '暴雨来临前认清家和车位附近的易涝点，提前挪车、挡水。',
    introUseTakeoutTitle: '外卖时机',
    introUseTakeout: '骑手要蹚过同样的水。地图大片深蓝时，缓一缓再下单。',
    introModelHeading: '模型怎么算',
    introModelIntro: '把彩云的网格降雨插值到约 280 米的地形格点上，每个格点跑一个逐小时的“水桶”模型：',
    fmLine1: '每小时　 W ← max(0, W + 雨量 × 0.8 − 10 × k)',
    fmLine2: '洼地系数 D = clamp(1 + 0.6 × (邻域均高 − 格点高程), 0.2, 3)',
    fmLine3: '积水指数 F = W × D　（F ≥ 5 可能积水，F ≥ 30 严重积水）',
    fmNote1: 'W 是格点滞留的水量（毫米），随时间累积；0.8 为径流系数——两成降雨渗入地面，其余汇入街道。',
    fmNote2: '10 mm/h 为标称排水能力，k 是「排水效率」滑块，拖动即重算整条时间线。',
    fmNote3: '洼地系数来自地形位置指数（TPI，±1.1 公里邻域）：低于周边的格点聚水，高于周边的格点排水。',
    introDataHeading: '数据来源',
    introDataRainTitle: '降雨 · 彩云天气',
    introDataRain: 'API v2.6，约 4.5 公里网格的逐小时降雨：过去 24 小时为观测/估计，未来 48 小时为预报，每 3 小时更新。',
    introDataTerrainTitle: '地形 · Copernicus GLO-30',
    introDataTerrain: '欧空局 30 米分辨率全球数字表面模型，按约 280 米格点取块均值。表面模型含建筑高度，故配色按 2%/98% 分位裁剪。',
    introDataBasemapTitle: '底图 · 高德地图',
    introDataBasemap: '底图为 GCJ-02 坐标系，所有数据坐标绘制前已由 WGS-84 转换。',
    introDocsLink: '文档 ↗',
    introDisclaimer: '所有积水程度均为模型估算，不是实测水深，不构成出行安全依据。',
    introStart: '开始使用',
    tourMap: '蓝色越深，预计积水越严重。点击地图任意位置，可查看该处 72 小时的积水变化曲线。',
    tourCity: '在这里切换城市。带 ?city= 参数的链接会直接打开对应城市。',
    tourDrainage: '模拟排水系统的好坏：调低它，看看排水不畅时哪里最先积水。',
    tourLegend: '三档积水程度。虚线框内才有地形数据，框外不是“无积水”，而是“未建模”。',
    tourElevation: '打开地形视图：等高线加高程配色，解释水为什么会在那里汇集。',
    tourTime: '从过去 24 小时拖到未来 48 小时。过去是估计，未来是预报。',
    tourPrev: '上一步',
    tourNext: '下一步',
    tourDone: '完成',
    tourSkip: '跳过',
  },
  en: {
    title: '{city} Flood Map',
    city: 'City',
    drainage: 'Drainage efficiency',
    drainageHint: 'Drag to simulate drainage quality',
    now: 'Now',
    estimated: 'Past (estimated)',
    predicted: 'Future (predicted)',
    bandNone: 'No significant water',
    bandPossible: 'Possible flooding',
    bandSevere: 'Severe flooding',
    legendDisclaimer: 'Model estimate, not measurements',
    showElevation: 'Show terrain elevation',
    elevationUnit: 'm',
    contourInterval: 'Contour interval',
    coverageNote: 'Dashed edge marks the modelled area; no terrain data outside',
    contourDetail: 'Contour detail',
    contourSmoothed: 'Interpolated smoothing, not finer terrain',
    updatedAt: 'Data updated',
    coverage: 'Coverage',
    loading: 'Loading…',
    noData: 'No rain data yet, refresh later',
    reports: 'Flood reports',
    langToggle: '中文',
    aboutBtn: 'About',
    tourBtn: 'Tour',
    introTagline: 'Real-time rainfall meets satellite terrain: an estimate of where city streets may flood, from 24 h ago to 48 h ahead.',
    introUsesHeading: 'What it’s for',
    introUseDrivingTitle: 'Driving',
    introUseDriving: 'Check the low spots along your route before you leave; steer around underpasses and culverts that may hold water.',
    introUsePreventTitle: 'Flood prep',
    introUsePrevent: 'Before a storm hits, learn the flood-prone ground near your home and parking spot — move the car and place barriers early.',
    introUseTakeoutTitle: 'Takeout timing',
    introUseTakeout: 'Couriers wade through the same water. When the map turns deep blue, maybe hold that order a while.',
    introModelHeading: 'How the model works',
    introModelIntro: 'Caiyun’s gridded rainfall is interpolated onto ~280 m terrain cells, and each cell runs an hourly “bucket” model:',
    fmLine1: 'each hour   W ← max(0, W + rain × 0.8 − 10 × k)',
    fmLine2: 'depression  D = clamp(1 + 0.6 × (area mean − cell elev), 0.2, 3)',
    fmLine3: 'flood index F = W × D   (F ≥ 5 possible, F ≥ 30 severe)',
    fmNote1: 'W is the water held at a cell (mm), accumulating hour by hour; 0.8 is the runoff coefficient — a fifth of the rain soaks in, the rest reaches the street.',
    fmNote2: '10 mm/h is the nominal drainage capacity and k is the drainage slider; dragging it recomputes the whole timeline.',
    fmNote3: 'The depression factor comes from the Topographic Position Index (TPI, ±1.1 km neighbourhood): cells below their surroundings collect water, cells above shed it.',
    introDataHeading: 'Data sources',
    introDataRainTitle: 'Rain · Caiyun Weather',
    introDataRain: 'API v2.6, hourly rainfall on a ~4.5 km grid: the past 24 h observed/estimated, the next 48 h forecast, refreshed every 3 h.',
    introDataTerrainTitle: 'Terrain · Copernicus GLO-30',
    introDataTerrain: 'ESA’s 30 m global digital surface model, block-averaged to ~280 m cells. A surface model includes buildings, so the colour ramp clips to the 2nd/98th percentiles.',
    introDataBasemapTitle: 'Basemap · AMap',
    introDataBasemap: 'The basemap uses GCJ-02 coordinates; every data coordinate is converted from WGS-84 before drawing.',
    introDocsLink: 'docs ↗',
    introDisclaimer: 'Every flood level here is a model estimate — not measured water depth, and not a basis for travel safety decisions.',
    introStart: 'Get started',
    tourMap: 'Deeper blue means more predicted ponding. Click anywhere on the map to see that spot’s 72-hour flood curve.',
    tourCity: 'Switch cities here. A link with ?city= opens that city directly.',
    tourDrainage: 'Simulate drainage quality: turn it down to see which streets flood first when the drains struggle.',
    tourLegend: 'Three flood bands. Terrain data exists only inside the dashed box — outside it means “not modelled”, not “no flooding”.',
    tourElevation: 'Toggle the terrain view: contour lines over a colour ramp show why water collects where it does.',
    tourTime: 'Drag from 24 h ago to 48 h ahead. Past hours are estimates; future hours are forecasts.',
    tourPrev: 'Back',
    tourNext: 'Next',
    tourDone: 'Done',
    tourSkip: 'Skip',
  },
} as const;

export type Lang = 'zh' | 'en';
let lang: Lang = (localStorage.getItem('lang') as Lang) || 'zh';
export const getLang = () => lang;
export function setLang(l: Lang) { lang = l; localStorage.setItem('lang', l); }

/** The current city's localized name, substituted into `{city}` by t(). */
let cityName: Record<Lang, string> = { zh: '', en: '' };
export function setCityName(n: Record<Lang, string>) { cityName = n; }

export function t(key: keyof typeof dict['zh']): string {
  return dict[lang][key].replace('{city}', cityName[lang]);
}
